spring.application.name=CRUD-MongoDB-Demo

# Local MongoDB connection
spring.mongodb.uri=mongodb://localhost:27017/mydb
# Optional: logging level for debugging
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

spring.main.allow-bean-definition-overriding=true


